// Post-codegen: emit the TS package barrels.
//   gen/ts/proto.ts  — re-exports every generated *_pb.ts
//   gen/ts/index.ts  — namespaced root export (proto / graphql / openapi) to avoid type collisions
//
// All inputs are generated artifacts; this file only stitches them. Run by `npm run gen`.
import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

const GEN = "gen/ts";

function walk(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name);
    return e.isDirectory() ? walk(p) : [p];
  });
}

// 1) proto barrel
const pbFiles = walk(join(GEN, "alchemist"))
  .filter((f) => f.endsWith("_pb.ts"))
  .sort();
const protoBarrel =
  "// AUTO-GENERATED by scripts/make-barrels.mjs — do not edit.\n" +
  pbFiles
    .map((f) => `export * from "./${relative(GEN, f).replace(/\.ts$/, ".js")}";`)
    .join("\n") +
  "\n";
writeFileSync(join(GEN, "proto.ts"), protoBarrel);

// 2) root index — namespaced so SE-1/AC-2 proto, CP-3 graphql, CP-2 openapi never collide
const parts = ['export * as proto from "./proto.js";'];
if (existsSync(join(GEN, "graphql.ts"))) parts.push('export * as graphql from "./graphql.js";');
if (existsSync(join(GEN, "openapi.ts"))) parts.push('export * as openapi from "./openapi.js";');
writeFileSync(
  join(GEN, "index.ts"),
  "// AUTO-GENERATED by scripts/make-barrels.mjs — do not edit.\n" + parts.join("\n") + "\n",
);

console.log(`barrels: ${pbFiles.length} proto module(s) -> ${GEN}/proto.ts, ${GEN}/index.ts`);
