"""alchemist_contracts — convenience facade over the generated boundary types.

Import boundary types from here (or directly from the generated ``alchemist.v0`` modules);
never hand-declare a shape that crosses a service boundary (see CLAUDE.md constitution).

    from alchemist_contracts import se1, ac2, domain
    utt = se1.Utterance(tenant_id="t1", call_id="c1", seq=1, text="hello", is_final=True)

The submodules are generated by `make gen` (buf → gen/py). If you see ImportError, run codegen.
"""

from alchemist.v0 import domain_pb2 as domain  # noqa: F401  CP-3/CP-2 domain source model
from alchemist.v0 import se1_pb2 as se1  # noqa: F401        SE-1 wire
from alchemist.v0 import ac2_pb2 as ac2  # noqa: F401        AC-2 tool schema

try:  # gRPC service stubs (optional at import time)
    from alchemist.v0 import se1_pb2_grpc as se1_grpc  # noqa: F401
    from alchemist.v0 import ac2_pb2_grpc as ac2_grpc  # noqa: F401
except ImportError:  # pragma: no cover - grpcio not installed
    se1_grpc = None
    ac2_grpc = None

try:  # CP-2 REST pydantic models (optional extra)
    from alchemist_contracts_openapi import models as openapi  # noqa: F401
except ImportError:  # pragma: no cover - openapi models not generated
    openapi = None

__all__ = ["domain", "se1", "ac2", "se1_grpc", "ac2_grpc", "openapi"]
